### ISSUE TITLE
`coingecko-api-v3` doesn't support the pro subscription from Coingecko

### ISSUE THREAD

**Issue by AhmedIbrahim336** [samuraitruong/coingecko-api-v3#13]
We are trying to migrate from free to pro subscription in Coingecko API. this doesn't sound good. As we have to reimplement 
the whole logic again. Another solution is **allow me to open a new pull request and implement the solution** 

Coingecko is using another base URL for the pro subscription `http://pro-api.coingecko.com`
also, it requires you to add a param whenever you are using the API `x_cg_pro_api_key `. you will be given the token when you create a premium account. I already have one so I can implement the solution.  
What do you think? @samuraitruong

**Comment by samuraitruong** [comment]
@AhmedIbrahim336  do you still need this? I can add support pro version however I dont have valid key to test. If you can do the PR it will be great
