### ISSUE TITLE
PLATFORMS enum is not correct

### ISSUE THREAD

**Issue by morph-dev** [samuraitruong/coingecko-api-v3#15]
The PLATFORMS enum is defined like this:
```
export type PLATFORMS = 'ethereum' | 'tron'
```
There are so many other platforms available.

In my opinion, this should be one of:

1. All returned by: `/asset_platforms`
1. All that appear in: `/coins/list?include_platform=true`
1. Doesn't exist at all, and if needed as type, `string` should be used as well (with additional documentation)
    - Since first 2 option require manual update every once in a while, this might be the most flexible approach

**Comment by samuraitruong** [comment]
@morph-dev  PLATFORMS type was defined when I made this lib so at that time it only have ethereum and tron. Maybe coingecko update their support now, I will check and extends that constants

**Comment by digimbyte** [comment]
resolved?

**Comment by souvik666** [comment]
@samuraitruong hey i have updated the platform enums https://github.com/samuraitruong/coingecko-api-v3/pull/41
