### ISSUE TITLE
Is it possible to pass the interval in minutes or in fractions of hours @ coinIdMarketChart()

### ISSUE THREAD

**Issue by codingholt** [samuraitruong/coingecko-api-v3#16]
Hey,
I would like to pass the interval in minutes or in fractions of hours is also fine, but don't know if that is possible, when writing this I'm getting the same response as when not declaring an interval:

```
await client.coinIdMarketChart({
        id: coin,
        vs_currency: 'usd',
        days: days,
        interval: '15min'
    })
```
or this:
```
await client.coinIdMarketChart({
        id: coin,
        vs_currency: 'usd',
        days: days,
        interval: '0.25h'
    })
```
don't know if it's possible, or just not supported by coingecko

thanks in advance 😃

**Comment by codingholt** [comment]
Figured out that, `interval: 'hourly'` works for 1 hour. But didn't figure out how to pass a fraction of an hour

**Comment by samuraitruong** [comment]
@codingholt pretty much reference to coingecko api,  I copy most of their document into the code so it can generate jsdoc. But if that document is out of date, maybe we need to update it.

**Comment by codingholt** [comment]
I think the intervals you can choose from are `hourly, daily, or weekly`? But sadly coingecko doesn't provide any documentation on this
