### ISSUE TITLE
package not being published correctly

### ISSUE THREAD

**Issue by vonoro** [samuraitruong/coingecko-api-v3#23]
hello, if you install latest from npm, you'll see that the `dist` folder is not present, basically the compiled source code is missing.

the last version that can be used is 0.0.13

**Comment by ChristianPerez34** [comment]
I experienced a similar issue as @vonoro 

Using version 0.0.13

**Comment by sebpalluel** [comment]
Same here:
![Screenshot 2022-10-30 at 17 16 00](https://user-images.githubusercontent.com/11297176/198889435-ad8fb6a2-27da-41e3-9433-3dd20dfbe9d9.png)

**Comment by dmytrotkk** [comment]
any updates on this one?
latest version is still broken

**Comment by samuraitruong** [comment]
got it, I am fixing it thanks

**Comment by samuraitruong** [comment]
@dmytrotkk  @ChristianPerez34  @tomholford  please check out the latest version 0.0.17

somehow, the republish command does not trigger, so enforce it in the CI  
![image](https://user-images.githubusercontent.com/1183138/212189077-03ed04a6-1efb-4d2b-9adb-83069546ade2.png)
