### ISSUE TITLE
Generate API site docs is down?

### ISSUE THREAD

**Issue by danger89** [samuraitruong/coingecko-api-v3#24]
https://samuraitruong.github.io/coingecko-api-v3/classes/coingeckoclient.coingeckoclient-1.html

**Comment by samuraitruong** [comment]
it is case sensitive, https://samuraitruong.github.io/coingecko-api-v3/classes/CoinGeckoClient.CoinGeckoClient-1.html

**Comment by danger89** [comment]
Well in that case you might want to update your readme!???
