### ISSUE TITLE
No support for PRO subscription

### ISSUE THREAD

**Issue by morph-dev** [samuraitruong/coingecko-api-v3#26]
note: I'm aware that there is #13 but that one is closed and I wanted to start new discussion.

The PRO subscription request has to ([source](https://coingeckoapi.notion.site/coingeckoapi/CoinGecko-Pro-API-exclusive-endpoints-529f4bb5c4d84d5fad797b09cfdb4b53)):

- go to separate url: `https://pro-api.coingecko.com/api/v3/`
- **pro_api_key** has to be included, either as request header `x-cg-pro-api-key` or request param `x_cg_pro_api_key`

I'm willing to make a PR for it.

Proposed approach:
- add optional **pro_api_key** to constructor
- If **pro_api_key** is set and non-empty:
  - change request endpoint
  - add **x-cg-pro-api-key** header

**Comment by morph-dev** [comment]
It's also worth noting that there are some API-s that are available only to PRO subscribers, but I don't plan to add those (at least not initially).

**Comment by 0xMobeus** [comment]
Support for api keys will be great.

**Comment by morph-dev** [comment]
I can make the PR. I even have api key that I can use to test and verify that it works.

**Comment by samuraitruong** [comment]
@cysedhu  I think this already merged with this PR https://github.com/samuraitruong/coingecko-api-v3/pull/31
