### ISSUE TITLE
api route /coins/markets

### ISSUE THREAD

**Issue by SanCrystal** [samuraitruong/coingecko-api-v3#34]
Using nodejs for the function "coinMarket" which does not correspond to the docs "coinMarkets". Also for some reason every end point function works fine but the "coinMarket" endpoint returns a 403 error

**Comment by samuraitruong** [comment]
maybe the API has changed, will check when I have time

**Comment by ozgunozerk** [comment]
Encountering the same issue. Can we prioritize this?

**Comment by samuraitruong** [comment]
will have a look today

**Comment by samuraitruong** [comment]
this.  API requires the user-agent that why it return 403. I am update the code to send defautl user-agent in the request and it working now, try to get new version after it published and confirm it work @ozgunozerk  @SanCrystal

**Comment by samuraitruong** [comment]
closed https://github.com/samuraitruong/coingecko-api-v3/commit/6a62c303ec95ac8e9adc2af2ccd96ef75e224181
